### ISSUE TITLE
Pushes to dev-master does not rebuild the distribution zip but works fine on dev-develop

### ISSUE THREAD

**Issue by lukeenglish** [lukaszlach/satis-server#16]
We have 2 main dev branches - dev-develop and dev-master

if we push to dev-develop the zip file on the satis server is rebuilt and when we run composer update we get the latest code. 

However if we do the same on dev-master and run composer update we see the latest commit being detected by composer but the zip file does not get re-generated and our code becomes outdated. 

If we add -prefer-source in composer then it works fine - the issue is with the “distribution packages” provided by this software.

Any ideas ? I’ve tried everything to try and fix the issue ! 

Thanks

**Comment by developedsoftware** [comment]
I am experiencing this issue also. 

edit: in that tags are built correctly but dev branches are not. They have the wrong commit hashes when pulled in from satis server. I suspect its some sort of cache that satis-server is doing. 

Any way to resolve?

**Comment by developedsoftware** [comment]
Solved by adding the below to the satis.json entry

cache-dir I think is the one that fixes it - as it essentially disabled the composer cache

```
    "require-all": true,
    "require-dependencies": true,
    "require-dev-dependencies": true,
    "config": {
        "cache-dir": "/dev/null"
    }
```

**Comment by developedsoftware** [comment]
This doesnt solve it - problem has came back! Nevermind. 

<img width="940" alt="Screenshot 2022-11-01 at 18 52 58" src="https://user-images.githubusercontent.com/19648131/199314825-5c0cf0c1-abbc-4245-a6f9-dd00212c0276.png">
