### ISSUE TITLE
POST zip file as package

### ISSUE THREAD

**Issue by MarWestermann** [lukaszlach/satis-server#8]
Hi,
I try to build a ci/cd solution for a composer project.
My idea was to have sth like a nexus repo which hosts the php packages written by me. This is possible with satis as you can place a package as zip file to the folder used as repository and now the package can be used by json.

But as all is running on openshift/kubernetes within their own docker containers I need a way to push/upload the zip file to the repository somehow.
Can this be done by the satis-server api?

Best regards, Marco

**Comment by markiewitch** [comment]
Hi Marco,
you're trying to setup a `ci/cd solution` so I guess you have some kind of VCS and one of the strengths of composer compared to JS world is that what you see in the repository is what you get after `composer require`. Wouldn't sending a `POST` to `/api/build` be enough?

**Comment by MarWestermann** [comment]
Hi. For our use case we use satis just as zip repo.. so satis is not aware of our git repo. We just want to push the zip file to the satis server.

**Comment by ichiriac** [comment]
Hi  @MarWestermann,

I've got the same need, you may be interested by this : https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#downloads
